---
# Server hostname that's DNS resolvable
server_hostname: "web01.prod.openstreetmap.ie"

# Hostname the site will be accessible from
site_hostname: "www.openstreetmap.ie"

# Database setup
# Variables will be passed to the MySql role
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_databases:
  - name: wordpress
mysql_users:
  - name: "{{ vault_mysql_wpuser }}"
    host: "%"
    password: "{{ vault_mysql_wpuser_password }}"
    priv: "wordpress.*:ALL"
    state: present


# certbot (external role vars)
certbot_admin_email: "{{ vault_certbot_admin_email }}"
certbot_certs:
  - domains:
    - "{{ server_hostname }}" # must be DNS resolvable


# Wordpress configuration
wordpress_site_title: "OpenStreetMap Ireland"
wordpress_admin_email: "{{ vault_wordpress_admin_email }}"
wordpress_admin_username: "{{ vault_wordpress_admin_username }}"
wordpress_admin_password: "{{ vault_wordpress_admin_password }}"
wordpress_plugins:
  - akismet
  - duo-wordpress
  - nginx-cache
  - osm
  - paid-memberships-pro
  - redis-cache
  - regenerate-thumbnails
  - updraftplus
  - wordpress-seo

# Plugins to install from inventories/<your_inventory>/files/plugins
# wordpress_zip_plugins:
#   - cool-plugin-7.0.0
#   - sweet-plugin-0.0.1

# Themes to install from inventories/<your_inventory>/files/plugins
# wordpress_zip_themes:
#   - my-cool-theme

# If you want a specific theme activated as part of the install, set it here
# wordpress_activate_theme: my-cool-theme

# If you want to import a database, put the file in inventories/<your_inventory>/files/database
# wordpress_database_export: export.sql

# Whether to enable nginx page caching
nginx_page_caching_enabled: false
